---
title: Reece Johnson Music
timezone: Europe/London
description: Music Producer, DJ, Artist

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md
