---
title: Tachyons Studio - CSS
timezone: Europe/London
description: Open source web components

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md
